export const USER_READ_REPOSITORY = 'USER_READ_REPOSITORY';
export const USER_WRITE_REPOSITORY = 'USER_WRITE_REPOSITORY';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
